services:
  unonextbot:
    build:
      context: .
    image: unonextbot:latest
    container_name: unonextbot
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    volumes:
      - ./:/app
    network_mode: bridge
